### PR TITLE
Move to c++17

### LINKED ISSUE #757: gtest C++14 requirement
Google Test since version 1.13.0 requires C++14:
```
[2/133] g++ -Itest/template.p -Iinclude -I../include -Isrc -I../src -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++11 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DGTEST_HAS_PTHREAD=1 -pthread -DWITH_TEST_DATA=1 -MD -MQ test/template.p/template.cpp.o -MF test/template.p/template.cpp.o.d -o test/template.p/template.cpp.o -c ../test/template.cpp
FAILED: test/template.p/template.cpp.o 
g++ -Itest/template.p -Iinclude -I../include -Isrc -I../src -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++11 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DGTEST_HAS_PTHREAD=1 -pthread -DWITH_TEST_DATA=1 -MD -MQ test/template.p/template.cpp.o -MF test/template.p/template.cpp.o.d -o test/template.p/template.cpp.o -c ../test/template.cpp
In file included from /usr/include/gtest/gtest-message.h:57,
                 from /usr/include/gtest/gtest-assertion-result.h:46,
                 from /usr/include/gtest/gtest.h:64,
                 from ../test/template.cpp:22:
/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~
```

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #757

All our compilers should handle c++17. Let's move on.

This PR also (re)add `werror=true` and fix different warnings (raised differently by different compilers)

### CODE REVIEW

File: include/zim/search_iterator.h [hunk 1]
```diff
@@ -32,10 +32,14 @@ namespace zim
...
 
-class LIBZIM_API SearchIterator : public std::iterator<std::bidirectional_iterator_tag, Entry>
+class LIBZIM_API SearchIterator
 {
     friend class zim::SearchResultSet;
     public:
+        using iterator_category = std::bidirectional_iterator_tag;
+        using value_type = Entry;
+        using pointer = Entry*;
+        using reference = Entry&;
```
Comment (veloman-yunkan) [inline include/zim/search_iterator.h:42]: The comment on `Archive::iterator` equally applies here too.

File: include/zim/suggestion_iterator.h [hunk 2]
```diff
@@ -31,11 +31,16 @@ class SuggestionResultSet;
...
+class LIBZIM_API SuggestionIterator
 {
     typedef Archive::iterator<EntryOrder::titleOrder> RangeIterator;
     friend class SuggestionResultSet;
     public:
+        using iterator_category = std::bidirectional_iterator_tag;
+        using value_type = SuggestionItem;
+        using pointer = SuggestionItem*;
+        using referenc = SuggestionItem&;
+
```
Comment (veloman-yunkan) [inline include/zim/suggestion_iterator.h:43]: The comment on `Archive::iterator` equally applies here too.

File: include/zim/suggestion_iterator.h [hunk 3]
```diff
@@ -31,11 +31,16 @@ class SuggestionResultSet;
...
-class LIBZIM_API SuggestionIterator : public std::iterator<std::bidirectional_iterator_tag, SuggestionItem>
+class LIBZIM_API SuggestionIterator
 {
     typedef Archive::iterator<EntryOrder::titleOrder> RangeIterator;
     friend class SuggestionResultSet;
     public:
+        using iterator_category = std::bidirectional_iterator_tag;
+        using value_type = SuggestionItem;
+        using pointer = SuggestionItem*;
+        using referenc = SuggestionItem&;
```
Comment (veloman-yunkan) [inline include/zim/suggestion_iterator.h:42]: Typo (which kind of illustrates that no code depends on `SuggestionIterator::reference` :wink:)

File: test/counterParsing.cpp [hunk 4]
```diff
@@ -142,59 +142,59 @@ TEST(ParseCounterTest, wrongType)
...
   {
     std::string counterStr = "text/html;raw=true=1";
-    CHECK(true, 1);
-    CHECK(false, 0);
-    CHECK(s.find("text/html") == 0, 1);
-    CHECK(s.find("text/html;raw=true") == 0, 1);
+    CHECK(true, 1U);
+    CHECK(false, 0U);
+    CHECK(s.find("text/html") == 0, 1U);
+    CHECK(s.find("text/html;raw=true") == 0, 1U);
```
Comment (veloman-yunkan) [inline test/counterParsing.cpp:148]: IMHO, the compilation warnings about signed-vs-unsigned mismatch in comparison expressions can be qualified as a compiler defect in situations where one of the expressions is a constant value within the safe range. Having said that, of course those warnings must be fixed, but in this particular case I would prefer if it was done by adjusting the definition of the `CHECK()` macro so that it uses a signed type for the variable `count`.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: include/zim/archive.h [hunk 5]
```diff
@@ -544,7 +544,7 @@ namespace zim
   class LIBZIM_API Archive::iterator
   {
     public:
-      using iterator_category = std::bidirectional_iterator_tag;
+      using iterator_category = std::input_iterator_tag;
```
Comment (veloman-yunkan) [inline include/zim/archive.h:547]: I disagree with this change for two reasons:

1. `Archive::iterator` is conceptually a bidirectional iterator (although it doesn't comply with all the requirements that STL has chosen to impose on its category of bidirectional iterators).
2. `Archive::iterator` is significantly more capable than STL's *`LegacyInputIterator`* since it can be used in multi-pass algorithms. *`LegacyInputIterator`* is about *other iterators* being invalidated, whereas the issue with `Archive::iterator` is that the `reference` obtained via `operator*` is invalidated as soon as the iterator is moved (unless `Archive::iterator::reference` is defined to be a value rather than a c++ reference).

The same argument goes for similar downshifts in `SearchIterator` and `SuggestionIterator`

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: include/zim/archive.h [hunk 6]
```diff
@@ -541,9 +541,14 @@ namespace zim
...
    */
   template<EntryOrder order>
-  class LIBZIM_API Archive::iterator : public std::iterator<std::bidirectional_iterator_tag, Entry>
+  class LIBZIM_API Archive::iterator
   {
     public:
+      using iterator_category = std::bidirectional_iterator_tag;
+      using value_type = Entry;
+      using pointer = Entry*;
+      using reference = Entry&;
```
[the remark this answers is not in the document]
Comment (veloman-yunkan) [reply include/zim/archive.h:550]: > It seems we are in the category of a [InputIterator](https://en.cppreference.com/w/cpp/named_req/InputIterator):
> 
> > LegacyInputIterators only guarantee validity for single pass algorithms: once a LegacyInputIterator i has been incremented, all copies of its previous value may be invalidated.

Yes and no. `LegacyInputIterator` is the lowest capability of iterators. If a type can be claimed to represent an iterator then it automatically satisfies the conceptual guarantees formulated for `LegacyInputIterator` (note, however, that it may also meet the syntax requirements). Thus `Archive::iterator` is a `LegacyInputIterator`

But `Archive::iterator` is far more capable than `LegacyInputIterator`. The problem is that it falls slightly short of complying with the requirements of `LegacyBidirectionalIterator`, which can be easily fixed at the cost of ABI breakage.

File: include/zim/archive.h (hunk 5 above)
Comment (mgautierfr) [reply include/zim/archive.h:547]: From [bidirectionalIterator](https://en.cppreference.com/w/cpp/named_req/BidirectionalIterator), a Legacy Bidirectional iterator is also a *[LegacyForwardIterator](https://en.cppreference.com/w/cpp/named_req/ForwardIterator)*

But from the note in ForwadIterator documentation, a *LegacyForwardIterator* reference must return a reference:

> Unlike the [std::forward_iterator](https://en.cppreference.com/w/cpp/iterator/forward_iterator) concept, the LegacyForwardIterator requirements requires dereference to return a reference.


(And `std::forward_iterator` is c++20 only)

I think we are stuck here. STL impose us some constraints we cannot provide as we create the object on demand instead of using one object stored in the container.
(I would be glad you prove me I'm wrong)

Declaring the iterator as STL LegacyInputIterator will limits only the STL. We may still document that iterator is kind of Bidirectional iterator but that referenced object must not be used after modification of iterator itself.

File: include/zim/archive.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (mgautierfr) [reply include/zim/archive.h:550]: Discussion continues in later review.
So I mark this one as resolved.

File: include/zim/archive.h (hunk 5 above)
Comment (mgautierfr) [reply include/zim/archive.h:547]: @veloman-yunkan Are we agree on this ? At least as a "non blocker issue, still to fix" ?
This PR is waited as the current global CI is broken and we need this PR to fix it.

Comment (veloman-yunkan) [reply include/zim/archive.h:547]: > (I would be glad you prove me I'm wrong)

Unfortunately, I have to disappoint you - you are perfectly right

> @veloman-yunkan Are we agree on this ?

With all the *input* provided let's move *forward* with the current code but explain in a comment (summarizing this discussion) the reason for `std::input_iterator_tag` in `Archive::iterator`, `SearchIterator` and `SuggestionIterator`.

Comment (mgautierfr) [reply include/zim/archive.h:564]: Done in a fixup commit.

**Review by veloman-yunkan — COMMENTED** [review]
Pre-approving. Fixup commits must be squashed. Squashup commits (if any) must be fixed.
