### PR TITLE
Correctly handle failing mmap on FileReader.

### LINKED ISSUE #866: LibZim 9.1 under macOS throws exception that cannot be caught
When trying to open a large ZIM file as of https://github.com/kiwix/apple/issues/675

The following exception is throw, which cannot be caught by Objective-C:
```
Kiwix`zim::(anonymous namespace)::makeMmappedBuffer:
    0x1028083a0 <+0>:   sub    sp, sp, #0x160
    0x1028083a4 <+4>:   stp    x24, x23, [sp, #0x120]
    0x1028083a8 <+8>:   stp    x22, x21, [sp, #0x130]
    0x1028083ac <+12>:  stp    x20, x19, [sp, #0x140]
    0x1028083b0 <+16>:  stp    x29, x30, [sp, #0x150]
    0x1028083b4 <+20>:  add    x29, sp, #0x150
    0x1028083b8 <+24>:  mov    x20, x3
    0x1028083bc <+28>:  mov    x23, x2
    0x1028083c0 <+32>:  mov    x22, x1
    0x1028083c4 <+36>:  mov    x21, x0
    0x1028083c8 <+40>:  mov    w0, #0x1d
    0x1028083cc <+44>:  bl     0x1029fc064               ; symbol stub for: sysconf
    0x1028083d0 <+48>:  neg    x8, x0
    0x1028083d4 <+52>:  and    x19, x8, x23
    0x1028083d8 <+56>:  mov    w8, #0x7fffffff
    0x1028083dc <+60>:  cmp    x19, x8
    0x1028083e0 <+64>:  b.hs   0x102808454               ; <+180>
    0x1028083e4 <+68>:  sub    x23, x23, x19
    0x1028083e8 <+72>:  add    x20, x23, x20
    0x1028083ec <+76>:  mov    x0, #0x0
    0x1028083f0 <+80>:  mov    x1, x20
    0x1028083f4 <+84>:  mov    w2, #0x1
    0x1028083f8 <+88>:  mov    w3, #0x2
    0x1028083fc <+92>:  mov    x4, x22
    0x102808400 <+96>:  mov    x5, x19
    0x102808404 <+100>: bl     0x1029fc310               ; symbol stub for: mmap
    0x102808408 <+104>: cmn    x0, #0x1
    0x10280840c <+108>: b.eq   0x10280847c               ; <+220>
    0x102808410 <+112>: mov    x22, x0
    0x102808414 <+116>: add    x19, x0, x23
    0x102808418 <+120>: str    x19, [x21]
    0x10280841c <+124>: mov    w0, #0x30
    0x102808420 <+128>: bl     0x1029fb560               ; symbol stub for: operator new(unsigned long)
    0x102808424 <+132>: adrp   x8, 2867
    0x102808428 <+136>: add    x8, x8, #0x9b8            ; vtable for std::__1::__shared_ptr_pointer<char*, zim::(anonymous namespace)::makeMmappedBuffer(int, zim::offset_t, zim::zsize_t)::$_0, std::__1::allocator<char>> + 16
    0x10280842c <+140>: stp    x8, xzr, [x0]
    0x102808430 <+144>: stp    xzr, x19, [x0, #0x10]
    0x102808434 <+148>: stp    x22, x20, [x0, #0x20]
    0x102808438 <+152>: str    x0, [x21, #0x8]
    0x10280843c <+156>: ldp    x29, x30, [sp, #0x150]
    0x102808440 <+160>: ldp    x20, x19, [sp, #0x140]
    0x102808444 <+164>: ldp    x22, x21, [sp, #0x130]
    0x102808448 <+168>: ldp    x24, x23, [sp, #0x120]
    0x10280844c <+172>: add    sp, sp, #0x160
    0x102808450 <+176>: ret    
    0x102808454 <+180>: mov    w0, #0x8
    0x102808458 <+184>: bl     0x1029fba88               ; symbol stub for: __cxa_allocate_exception
    0x10280845c <+188>: adrp   x8, 2867
    0x102808460 <+192>: add    x8, x8, #0x990            ; vtable for zim::(anonymous namespace)::MMapException + 16
    0x102808464 <+196>: str    x8, [x0]
    0x102808468 <+200>: adrp   x1, 2867
    0x10280846c <+204>: add    x1, x1, #0x8d8            ; typeinfo for zim::(anonymous namespace)::MMapException
    0x102808470 <+208>: adrp   x2, 0
    0x102808474 <+212>: add    x2, x2, #0x39c            ; zim::(anonymous namespace)::MMapException::~MMapException()
    0x102808478 <+216>: bl     0x1029fb518               ; symbol stub for: __cxa_throw
->  0x10280847c <+220>: add    x0, sp, #0x18
    0x102808480 <+224>: bl     0x1027fb8c0               ; std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_ostringstream[abi:v160006]()
    0x102808484 <+228>: adrp   x1, 567
    0x102808488 <+232>: add    x1, x1, #0x76e            ; "Cannot mmap size "
    0x10280848c <+236>: add    x0, sp, #0x18
    0x102808490 <+240>: mov    w2, #0x11
    0x102808494 <+244>: bl     0x1027f69f0               ; std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence[abi:v160006]<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long)
    0x102808498 <+248>: mov    x1, x20
    0x10280849c <+252>: bl     0x1029fb9ec               ; symbol stub for: std::__1::basic_ostream<char, std::__1::char_traits<char>>::operator<<(unsigned long long)
    0x1028084a0 <+256>: adrp   x1, 567
    0x1028084a4 <+260>: add    x1, x1, #0x780            ; " at off "
    0x1028084a8 <+264>: mov    w2, #0x8
    0x1028084ac <+268>: bl     0x1027f69f0               ; std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence[abi:v160006]<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long)
    0x1028084b0 <+272>: mov    x1, x19
    0x1028084b4 <+276>: bl     0x1029fb9ec               ; symbol stub for: std::__1::basic_ostream<char, std::__1::char_traits<char>>::operator<<(unsigned long long)
    0x1028084b8 <+280>: adrp   x1, 567
    0x1028084bc <+284>: add    x1, x1, #0x5c2            ; " : "
    0x1028084c0 <+288>: mov    w2, #0x3
    0x1028084c4 <+292>: bl     0x1027f69f0               ; std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence[abi:v160006]<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long)
    0x1028084c8 <+296>: mov    x19, x0
    0x1028084cc <+300>: bl     0x1029fc2b0               ; symbol stub for: __error
    0x1028084d0 <+304>: ldr    w0, [x0]
    0x1028084d4 <+308>: bl     0x1029fbee4               ; symbol stub for: strerror
    0x1028084d8 <+312>: mov    x20, x0
    0x1028084dc <+316>: bl     0x1029fbf5c               ; symbol stub for: strlen
    0x1028084e0 <+320>: mov    x2, x0
    0x1028084e4 <+324>: mov    x0, x19
    0x1028084e8 <+328>: mov    x1, x20
    0x1028084ec <+332>: bl     0x1027f69f0               ; std::__1::basic_ostream<char, std::__1::char_traits<char>>& std::__1::__put_character_sequence[abi:v160006]<char, std::__1::char_traits<char>>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, char const*, unsigned long)
    0x1028084f0 <+336>: mov    w0, #0x10
    0x1028084f4 <+340>: bl     0x1029fba88               ; symbol stub for: __cxa_allocate_exception
    0x1028084f8 <+344>: mov    x19, x0
    0x1028084fc <+348>: add    x8, sp, #0x18
    0x102808500 <+352>: add    x0, x8, #0x8
    0x102808504 <+356>: mov    x8, sp
    0x102808508 <+360>: bl     0x1029fb9a4               ; symbol stub for: std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char>>::str() const
    0x10280850c <+364>: mov    w21, #0x1
    0x102808510 <+368>: mov    x1, sp
    0x102808514 <+372>: mov    x0, x19
    0x102808518 <+376>: bl     0x1029fb6a4               ; symbol stub for: std::runtime_error::runtime_error(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)
    0x10280851c <+380>: mov    w21, #0x0
    0x102808520 <+384>: adrp   x1, 2830
    0x102808524 <+388>: ldr    x1, [x1, #0x988]
    0x102808528 <+392>: adrp   x2, 2830
    0x10280852c <+396>: ldr    x2, [x2, #0x9c0]
    0x102808530 <+400>: mov    x0, x19
    0x102808534 <+404>: bl     0x1029fb518               ; symbol stub for: __cxa_throw
    0x102808538 <+408>: b      0x102808594               ; <+500>
    0x10280853c <+412>: mov    x20, x0
    0x102808540 <+416>: ldrsb  w8, [sp, #0x17]
    0x102808544 <+420>: tbz    w8, #0x1f, 0x102808558    ; <+440>
    0x102808548 <+424>: ldr    x0, [sp]
    0x10280854c <+428>: bl     0x1029fbaf4               ; symbol stub for: operator delete(void*)
    0x102808550 <+432>: tbnz   w21, #0x0, 0x102808564    ; <+452>
    0x102808554 <+436>: b      0x102808574               ; <+468>
    0x102808558 <+440>: cbnz   w21, 0x102808564          ; <+452>
    0x10280855c <+444>: b      0x102808574               ; <+468>
    0x102808560 <+448>: mov    x20, x0
    0x102808564 <+452>: mov    x0, x19
    0x102808568 <+456>: bl     0x1029fb65c               ; symbol stub for: __cxa_free_exception
    0x10280856c <+460>: b      0x102808574               ; <+468>
    0x102808570 <+464>: mov    x20, x0
    0x102808574 <+468>: add    x0, sp, #0x18
    0x102808578 <+472>: bl     0x1027f4bc0               ; std::__1::basic_ostringstream<char, std::__1::char_traits<char>, std::__1::allocator<char>>::~basic_ostringstream()
    0x10280857c <+476>: b      0x1028085a0               ; <+512>
    0x102808580 <+480>: bl     0x1029fb848               ; symbol stub for: __cxa_begin_catch
    0x102808584 <+484>: mov    x0, x22
    0x102808588 <+488>: mov    x1, x20
    0x10280858c <+492>: bl     0x1029fc1d8               ; symbol stub for: munmap
    0x102808590 <+496>: bl     0x1029fb578               ; symbol stub for: __cxa_rethrow
    0x102808594 <+500>: brk    #0x1
    0x102808598 <+504>: mov    x20, x0
    0x10280859c <+508>: bl     0x1029fb9c8               ; symbol stub for: __cxa_end_catch
    0x1028085a0 <+512>: mov    x0, x20
    0x1028085a4 <+516>: bl     0x1029fc5c8               ; symbol stub for: _Unwind_Resume
    0x1028085a8 <+520>: bl     0x1022c8764               ; __clang_call_terminate

```

### PR DESCRIPTION
**Pull request by mgautierfr**
If we try to mmap a region to high (>4GB), `makeMmappedBuffer` will throw a `MMapException`. In this case, we want to do a read in the file instead of mmap.

This case is handled in `MultiPartFileReader` but was missing in `FileReader`.

Fix #866

### CODE REVIEW

**Comment by mgautierfr** [comment]
@BPerlakiH can you test this on your side ?

**Comment by BPerlakiH** [comment]
@mgautierfr I have tested with this branch by replacing it in `kiwix-build`:
```
diff --git a/kiwixbuild/dependencies/libzim.py b/kiwixbuild/dependencies/libzim.py
index a57e69e..88dfbd6 100644
--- a/kiwixbuild/dependencies/libzim.py
+++ b/kiwixbuild/dependencies/libzim.py
@@ -9,7 +9,7 @@ class Libzim(Dependency):
     class Source(GitClone):
         git_remote = "https://github.com/openzim/libzim.git"
         git_dir = "libzim"
-        git_ref = "trace_mmap_macos"
+        git_ref = "fix_macos_mmap"
 
     class Builder(MesonBuilder):
         test_options = ["-t", "8"]
```
and it is still crashing at the same point with:
```
mmap with flags:2 offest:0 size:80
munmap 4780654592 size:80
pageAlignedOffset (8416296960) is too big
```

**Comment by mgautierfr** [comment]
This branch doesn't have traces. So if you have this output you probably not testing the right thing.

**Comment by kelson42** [comment]
@mgautierfr Are we not impacted by https://github.com/kiwix/kiwix-build/issues/32? Are we sure that kiwix-build has the HEAD of the proper branch?

**Comment by mgautierfr** [comment]
@BPerlakiH you have to checkout yourself the right branch (but as you already done it for `trace_mmap_macos`, I suspect you are good with this)

> Are we not impacted by https://github.com/kiwix/kiwix-build/issues/32?

No. A checkout to the right branch and a build (of libzim AND libkiwix (as libkiwix is statically linked to libzim)) and you should be ok (`kiwix-build libkiwix --config ...` already compile all dependencies of libkiwix by default)

> Are we sure that kiwix-build has the HEAD of the proper branch?

If there is no modification of the code (clean working directory) and kiwix-build is configured to get the branch you are on (see https://github.com/kiwix/kiwix-build/commit/2359d0997f44853fd24067322e10cd5ca0a41d83 for example), kiwix-build update the source code automatically

Of course, all this is true if you don't ask to not do it (`--skip-source-prepare`, `--build-nodeps`)

**Comment by mgautierfr** [comment]
@veloman-yunkan please review without waiting confirmation for @BPerlakiH, I'm pretty confident it is a real bug and we should merge it, whatever it fixes the linked issue or not.

File: src/file_reader.cpp [hunk 1]
```diff
@@ -201,7 +201,10 @@ const Buffer MultiPartFileReader::get_buffer(offset_t offset, zsize_t size) cons
   } catch(MMapException& e)
 #endif
   {
-    // The range is several part, or we are on Windows.
+    // We cannot do the mmap, for several possible reasons:
+    // - Mmap offset is too big (>4GB on 32 bits)
+    // - The range is several part
+    // - We are on Windows.
```
Comment (veloman-yunkan) [inline src/file_reader.cpp:207]: Please look into `mmapReadOnly()` which is `libzim`'s wrapper around `mmap()` - if the `mmap()` syscall fails a `std::runtime_error` (rather than a `MMapException`) is thrown. I think it must be fixed. Then you will have to add another case to this list.

File: src/file_reader.cpp [hunk 2]
```diff
@@ -278,14 +281,22 @@ const Buffer FileReader::get_buffer(offset_t offset, zsize_t size) const
...
+  try {
+    auto local_offset = offset + _offset;
+    int fd = _fhandle->getNativeHandle();
+    return Buffer::makeBuffer(makeMmappedBuffer(fd, local_offset, size), size);
+  } catch(MMapException& e)
 #endif
+  {
+    // We cannot do the mmap, for several possible reasons:
+    // - Mmap offset is too big (>4GB on 32 bits)
+    // - We are on Windows.
```
Comment (veloman-yunkan) [inline src/file_reader.cpp:293]: After the bug in `mmapReadOnly()` is fixed, this comment must be updated too.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
While reviewing this PR, I seem to have found another bug. I believe its fix should be included in this PR (and the title and description of the PR properly updated).

**Review by veloman-yunkan — COMMENTED** [review]
And what do you think of introducing a base class for `FileReader` and `MultiPartFileReader` that will provide a partial implementation of the `get_buffer_method()` in terms of a new virtual function `get_mmapped_buffer()`? Such a class can also be a common place for the data members `_offset` and `_size` and their accessor methods.

**Comment by BPerlakiH** [comment]
> @BPerlakiH you have to checkout yourself the right branch (but as you already done it for `trace_mmap_macos`, I suspect you are good with this)

@mgautierfr  I am not sure about this part. I did as described earlier, changing the `git_ref` in the file: `kiwixbuild/dependencies/libzim.py`.
I did `git clean -dfx` before to delete the old build files. I did clean derived data on Xcode, but I am still getting the same results, it is still tracing and still crashing. I tried it 3 or 4 times with different combinations of clearing things first...

Maybe we need a more step by step instructions how to build this the right way, or if you could send me a complete xcframework built with your changes, that would be even easier for me to test.

**Comment by rgaudin** [comment]
When @mgautierfr mentions a clean state, I believe you need to remove `SOURCE/libzim` and `SOURCE/libkiwix` as well. you can check the git branch in those folders post-build to verify which branch was actually used

File: src/file_reader.cpp (hunk 1 above)
Comment (mgautierfr) [reply src/file_reader.cpp:207]: I have think about that, but if the mmap fails, the read will probably fail too. (Or if we mmap a too big size, we may allocation a too big size too).

But we can indeed try our chance and crash later if we cannot read.

**Comment by mgautierfr** [comment]
I have launch a new build for provide you a xcframework.

>  I am not sure about this part. I did as described earlier, changing the git_ref in the file: kiwixbuild/dependencies/libzim.py.

You should not. The `git_ref` is used:
- When no source is set, kiwix-build will checkout the git_ref.
- When source is set, it will update the source ONLY if our git directory is clean and you haven't not change the branch (git_ref == current git branch). (The idea is that it update everything you haven't touch and don't remove your changes).

If you change the `git_ref` after a first run, git_ref != current git branch and update is not made (You should have a warning in the output).

You can directly goes into `SOURCE/libzim` and run `git remote update && git pull fix_macos_mmap`. If you don't have change `git_ref`, `git_ref != fix_macos_mmap`, kiwix-build will not change the source, so you will compile `fix_macos_mmap`.

Or you can remove `SOURCE/libzim`, (and update `git_ref`) so kiwix-build will download again the source and switch to `git_ref` before compiling.

**Comment by BPerlakiH** [comment]
Thank you @mgautierfr ,
I can confirm it is fixing the issue!
See below, "Canadian Prepper" now opens correctly:
Screenshot 2024-03-29 at 10 59 37 Medium

**Comment by mgautierfr** [comment]
> And what do you think of introducing a base class for FileReader and MultiPartFileReader that will provide a partial implementation of the get_buffer() method in terms of a new virtual function get_mmapped_buffer()? Such a class can also be a common place for the data members _offset and _size and their accessor methods.

I think well about this. I will do it.

**Comment by mgautierfr** [comment]
> I will do it.

Done. Ready for another review.

File: src/file_reader.h [hunk 3]
```diff
@@ -36,6 +36,12 @@ class BaseFileReader : public Reader {
     zsize_t size() const { return _size; };
     offset_t offset() const { return _offset; };
 
+#ifdef ENABLE_USE_MMAP
+    virtual const Buffer get_mmap_buffer(offset_t offset,
+                                         zsize_t size) const = 0;
+#endif
```
Comment (veloman-yunkan) [inline src/file_reader.h:42]: This feels a little like making the ABI dependent on compilation options. Upon further contemplation it seems safe but I would prefer if the conditional compilation is restricted to the .cpp files.

**Review by veloman-yunkan — COMMENTED** [review]
I have only one slight concern. If it is unjustified paranoia then this is an approval.

File: src/file_reader.h (hunk 3 above)
Comment (mgautierfr) [reply src/file_reader.h]: Done in fixup commit.

**Review by veloman-yunkan — COMMENTED** [review]
LGTM. Rebase&fixup is due.

**Comment by mgautierfr** [comment]
> LGTM. Rebase&fixup is due.

Done

**Review by veloman-yunkan — APPROVED** [review]
