### PR TITLE
Fixes #502 File name consistent with input provided

### LINKED ISSUE #502: Created zim file should have the name provided as input
Currently, the ".zim" extension is automatically added to the created file irrespective of it being in the input name user provides. This can cause some unexpected behavior and results such as:
- The temporary test zim files created using `zim::unittests::TempFile` are not getting removed
- We expect the output file name to be the same as the input provided

### PR DESCRIPTION
**Pull request by maneeshpm**
Fixes #502 

`".zim"` extension is not automatically added to the output file path if it is not provided by the user in the input.

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Would be good you validate this PR as well as this will probably impact all scrapers.
@rgaudin Ping as well

File: test/creator.cpp [hunk 1]
```diff
@@ -96,7 +96,7 @@ void test_redirect_dirent(
 TEST(ZimCreator, createEmptyZim)
 {
   unittests::TempFile temp("emptyzimfile");
-  auto tempPath = temp.path() + ".zim";
+  auto tempPath = temp.path();
   writer::Creator creator;
   creator.startZimCreation(tempPath);
```
Comment (veloman-yunkan) [inline test/creator.cpp:101]: So, I had overlooked this fictitious usage of `TempFile` in #493, which resulted in the temporary ZIM file being left behind/not deleted. There is nothing to do about this comment, just documenting my own negligence in order to prevent some of it in the future.

**Review by veloman-yunkan — APPROVED** [review]
This change may break some flows relying on the ".zim" extension being automatically added to the output file name. The final word belongs to @mgautierfr and @rgaudin.

**Comment by veloman-yunkan** [comment]
> Fixes #502
> 
> setting `basename` = `fname` inside `CreatorData` and using basename directly in rename in `finishZimCreation()`.

@maneeshpm It's better to describe the changes from the conceptual point of view. In this particular case what matters is that the ".zim" extension is not automatically added to output file path without it.

**Comment by maneeshpm** [comment]
Thank you for the information @veloman-yunkan! Modifying the description. Will remember that for future PRs.

**Comment by rgaudin** [comment]
> This change may break some flows relying on the ".zim" extension being automatically added to the output file name. The final word belongs to @mgautierfr and @rgaudin.

Doesn't break pylibzim as we don't use `CreatorData` but directly call `startZimCreation` with our in-python defined path

File: src/writer/creator.cpp [hunk 2]
```diff
@@ -406,10 +406,8 @@ namespace zim
         nbUnCompClusters(0),
         start_time(time(NULL))
     {
-      basename =  (fname.size() > 4 && fname.compare(fname.size() - 4, 4, ".zim") == 0)
-                        ? fname.substr(0, fname.size() - 4)
-                        : fname;
-      auto zim_name = basename + ".zim.tmp";
+      basename = fname;
```
Comment (mgautierfr) [inline src/writer/creator.cpp:409]: It would be better to initialize `basename` in the initializer list.

**Review by mgautierfr — CHANGES_REQUESTED** [review]
Now, `basename` is not the base name but the final filename.
And `zim_name` is not the zim name (and never was) but the tmp filename.
(And it would be nice to store it to not have to recompute it when we rename it).

**Comment by mgautierfr** [comment]
Apart from the code review itself (which is technically functional), I wonder if this is a feature we want.

The usage is to have the extension specifying the type of the file. It makes sens to add the final `.zim` extension if it is missing.

> The temporary test zim files created using zim::unittests::TempFile are not getting removed [From #502]

Could be fixed by adding the ".zim" to the name of the TempFile.

> Doesn't break pylibzim as we don't use CreatorData but directly call startZimCreation with our in-python defined path

`startZimCreation` is using `CreatorData`. You are impacted by this change : If the path is missing the extension, it will not be added (it is for now).
All "writer" will be impacted the same way.

**Comment by rgaudin** [comment]
> > Doesn't break pylibzim as we don't use CreatorData but directly call startZimCreation with our in-python defined path
> 
> `startZimCreation` is using `CreatorData`. You are impacted by this change : If the path is missing the extension, it will not be added (it is for now).
> All "writer" will be impacted the same way.

Ah! OK then.

**Comment by kelson42** [comment]
> Apart from the code review itself (which is technically functional), I wonder if this is a feature we want.
> 
> The usage is to have the extension specifying the type of the file. It makes sens to add the final `.zim` extension if it is missing.

This should probably have been discussed in the ticket, but to my opinion this is not the duty of the libzim to enforce anything regarding the filename. There is no value to do so, to the contrary like we can see. We are not building here a end-user product for dummy users. I believe, the lizim should do whatever as been requested by the developer, not take decision for him and not make something else, even if this "something else" might have some arguments in favour.

**Comment by mgautierfr** [comment]
Both point of view are good. I've no strong opinion on this.

Just want to be sure we are agree with the change. (libzim may not enforce the extension, but then no tools will enforce it as we were relying on libzim to do it. So we may want to add this enforcement in other tools).

**Comment by kelson42** [comment]
> Just want to be sure we are agree with the change. (libzim may not enforce the extension, but then no tools will enforce it as we were relying on libzim to do it. So we may want to add this enforcement in other tools).

Yes, I'm far more open to the idea to implement such a feature at a higher level if a maintainer is strongly in favour.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan If we agree on principle and on code (I believe @maneeshpm has taken in account all your remarks), would be good to merge this PR today, as this is quite blocking the other suggestions related PR in the pipe.

File: src/writer/creator.cpp [hunk 3]
```diff
@@ -404,20 +404,20 @@ namespace zim
         nbClusters(0),
         nbCompClusters(0),
         nbUnCompClusters(0),
-        start_time(time(NULL))
+        start_time(time(NULL)),
+        basename(fname)
```
Comment (mgautierfr) [inline src/writer/creator.cpp:408]: It would be better to rename `basename` to `zimName`

File: src/writer/creator.cpp [hunk 4]
```diff
@@ -404,22 +404,20 @@ namespace zim
...
     {
-      basename =  (fname.size() > 4 && fname.compare(fname.size() - 4, 4, ".zim") == 0)
-                        ? fname.substr(0, fname.size() - 4)
-                        : fname;
-      auto zim_name = basename + ".zim.tmp";
+      tempFileName = basename + ".tmp";
```
Comment (mgautierfr) [inline src/writer/creator.cpp:410]: This can also be moved in the initializer list.

**Review by mgautierfr — CHANGES_REQUESTED** [review]
Just two small changes and we are good.

**Comment by veloman-yunkan** [comment]
> @mgautierfr @veloman-yunkan If we agree on principle and on code (I believe @maneeshpm has taken in account all your remarks), would be good to merge this PR today, as this is quite blocking the other suggestions related PR in the pipe.

The following remark by @mgautierfr has not been addressed:

> Now, `basename` is not the base name but the final filename.

It is trivial to fix. Yet, I don't think that the world will break even if we merge without that correction.

**Comment by mgautierfr** [comment]
Please rewrite a bit the history. There are several logical "changes" in this pr (and so, same number of commits) :
- Do not change the path provided.
- Rename the variable names.
- (Maybe) introduce the tmpFileName member (can be squash with previous commit, as a "variable cleanup").

It is up to you to split the PR in logical changes, but we should not have commits fixing previous commit of the same PR. Commits must show the logical changes, not the tries you've made (comments/review in PR are enough)

**Comment by maneeshpm** [comment]
Thanks @mgautierfr! It looks much neater now.

**Review by mgautierfr — APPROVED** [review]

**Comment by mgautierfr** [comment]
Missing code coverage is about the error handling if we cannot create the file.
Failing windows CI is not related to this PR.

I'm merging.
