### PR TITLE
Non-word symbol friendly suggestions

### LINKED ISSUE #536: Xapian queryparser fails when the querystring contains ampersand or other non words
Refer openzim/libzim@f667d38
We get a xapian exception while trying to parse "Alice & Bob".  The error arises because Xapian operators `OP_PHRASE` and `OP_NEAR` only support leaf subqueries.

### LINKED ISSUE #537: Handling of non-words in publisher query
The approach used in `publisherQuery()` for building a phrase query
enforcing the specified prefix for all terms fails if the input phrase
contains a term that Xapian's query parser doesn't like (e.g. a
standalone ampersand character, 1/2, a#1, etc).

Using the `quest` tool (coming with xapian-tools under Ubuntu) the
issue can be demonstrated as follows:

```
$ quest -o phrase -d some_xapian_db "Energy & security act"
UnimplementedError: OP_NEAR and OP_PHRASE only currently support leaf subqueries

$ quest -o phrase -d some_xapian_db 'Energy 1/2 security act'
UnimplementedError: OP_NEAR and OP_PHRASE only currently support leaf subqueries

$ quest -o phrase -d some_xapian_db "Energy a#1 security act"
UnimplementedError: OP_NEAR and OP_PHRASE only currently support leaf subqueries
```

The problem comes from parsing the query with the default operation set
to `OP_PHRASE` (exemplified by the `-o phrase` option in above
invocations of `quest`). A workaround is to parse the phrase with a
default operation of `OP_OR` and then combine all the terms with
`OP_PHRASE`.

This issue is likely to be present in libzim/src/search.cpp too, where
`set_default_op(Xapian::Query::op::OP_PHRASE)` is used. It affects
suggestions in my local build of kiwix-serve (though the instance
running at library.kiwix.org seems to be unaffected, is it an old
version?).

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #537

> @maneeshpm This PR demonstrates a issue discovered during the work on kiwix/kiwix-lib#488 (for more details see commit https://github.com/kiwix/kiwix-lib/pull/488/commits/e5399be066c05b3f065d7d4542c48a0d4fa721e2). The workaround utilized in the said PR doesn't work for libzim out-of-the-box because it breaks some unit tests.
> 
> Would you mind taking over this PR and completing it?

Fixes #536 

The issue is Xapian queryparser does not work with `OP_PHRASE`/`OP_NEAR` as the default operator on certain kinds of queries. To fix this, we can change the default operator to `OP_OR` and bind the terms in a subquery that is created using query constructor with `OP_PHRASE` to handle the phrasing.

The changes included in this PR are:
- Add a unittest `nonWordCharacters` to suggestions.
- Switch default operator to `OP_OR`

### CODE REVIEW

**Comment by maneeshpm** [comment]
@veloman-yunkan Sure! I'll love to pick this us.

**Comment by kelson42** [comment]
@maneeshpm Please open corresponding ticket

**Comment by maneeshpm** [comment]
@veloman-yunkan I have added a couple of similar tests. Can you confirm if this the behavior which we expect?

File: src/search.cpp [hunk 1]
```diff
@@ -137,7 +137,8 @@ Xapian::Query parse_query(Xapian::QueryParser* query_parser, std::string qs, int
 
     if (suggestion_mode && !query.empty()) {
       Xapian::Query subquery_phrase, subquery_anchored;
-      query_parser->set_default_op(Xapian::Query::op::OP_AND);
+      query_parser->set_default_op(Xapian::Query::op::OP_OR);
+      query_parser->set_stemming_strategy(Xapian::QueryParser::STEM_NONE);
```
Comment (veloman-yunkan) [inline src/search.cpp]: It's `set_stemming_strategy(Xapian::QueryParser::STEM_NONE)` that fixes the failure of the `Suggestion` unit-tests broken by the original "bad" fix. Is there any reason for using `OP_OR` instead of `OP_AND`? What negative effects may disabling of stemming have in this case?

File: test/suggestion.cpp [hunk 2]
```diff
@@ -87,6 +87,12 @@ namespace {
     return result;
   }
 
+#define EXPECT_SUGGESTION_RESULTS(archive, query, ...)          \
```
Comment (veloman-yunkan) [inline test/suggestion.cpp:90]: What do you think about using this macro in the other `Suggestion` unit-tests (but of course not in this PR)?

**Review by veloman-yunkan — COMMENTED** [review]
Cool that you found such a simple fix!

The history/commit messages of this PR must be changed before merging.

File: src/search.cpp (hunk 1 above)
Comment (maneeshpm) [reply src/search.cpp]: The stemmed terms do not have a `positionList` associated with them. They are just words, so they cannot be used for an `OP_PHRASE`. The bad fix used `OP_AND` which enforced stemming. Hence, the bad fix failed the older tests.

Disabling stemming won't have any effect at all compared to before this PR. It's by default disabled when we used `OP_PHRASE` as the default operator.

Using `OP_AND` instead of `OP_OR` won't have any significant impact. I felt that it is a better indicator of our motive here that we are only using it to get proper tokenizing into separate terms and the actual work is done by `OP_PHRASE` subquery.

File: test/suggestion.cpp (hunk 2 above)
Comment (maneeshpm) [reply test/suggestion.cpp:90]: To be honest it's pretty elegant :smile: A product of experience I guess. I will keep updating the rest of the tests whenever I get the chance with this macro.

**Review by veloman-yunkan — COMMENTED** [review]
@maneeshpm Please rewrite the history of this PR and then it can be merged (GitHub won't let me approve it for the same reason I cannot be made a reviewer).

**Review by maneeshpm — APPROVED** [review]
@veloman-yunkan Commit rewritten, rebase done.

**Comment by kelson42** [comment]
@maneeshpm Looks like you had forgotten to have no steemming for the title search. But we have not test securing the no steeming works!

**Comment by maneeshpm** [comment]
@kelson42 We can be sure that `STEM_NONE` is working because phrase search is working. As I mentioned in my comment [here](https://github.com/openzim/libzim/pull/534#discussion_r614348560), OP_PHRASE works only with non stemmed terms. Earlier, when we had `OP_PHRASE` as the default operator, it enforced this by itself. Now that we are using `OP_OR` as the default operator, we need to enforce this ourselves so that OP_PHRASE can work.
