### PR TITLE
Validation of MIME-type values in dirents

### LINKED ISSUE #376: zimcheck should catch zimfiles with invalid mimetype list.
Recent zim files created by zimwriterfs are broken (https://github.com/openzim/zimwriterfs/issues/48)
zimcheck should be extended to catch them.

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #376

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
CodeFactor complains about code complexity in src/fileimpl.cpp without pointing specifically to a particular method/function. The only new function introduced in that file is `FileImpl::checkDirentMimeTypes()` which isn't particularly complex. An attempt to make CodeFactor happy didn't succeed. I am not going to worry about that only "failure" in CI.

**Comment by kelson42** [comment]
@veloman-yunkan Fine to me, it is ture that the "complex function" issue is not allway super pertinent. I have asked Codefactor to specificaly ignore this error for this function.

File: src/fileimpl.cpp [hunk 1]
```diff
@@ -440,7 +440,7 @@ makeFileReader(std::shared_ptr<const FileCompound> zimFile, offset_t offset, zsi
 
   const std::string& FileImpl::getMimeType(uint16_t idx) const
   {
-    if (idx > mimeTypes.size())
+    if (idx >= mimeTypes.size())
```
Comment (mgautierfr) [inline src/fileimpl.cpp:443]: Nice catch.

It would be nice to test this.
It should be easily doable if we create a `FileImpl` (instead of Archive) on any existing file and directly call `getMimeType`.

It would even be better to move the mimetype handling in a separated object, as we've done for direntReader/direntAccessor/direntLookup/...
But it should be done in a separated PR (I'm open to add the test in this new PR, if we do it soon)

**Review by mgautierfr — CHANGES_REQUESTED** [review]

File: src/fileimpl.cpp (hunk 1 above)
Comment (veloman-yunkan) [reply src/fileimpl.cpp:443]: Creating a new unit-test for this small (trivial and obviously correct) fix doesn't fit well into this PR. Let's do it in a separate refactoring PR focusing on mimetype handling.

**Review by mgautierfr — APPROVED** [review]
