### PR TITLE
Be more tolerant to threads scheduling in unit tests.

### LINKED ISSUE #747: Async error testing must be more tolerant to asynchronous workers scheduling.
AsyncError are by nature detected asynchronously.
On slow computer (CI) the worker threads may not run it time and test fails.
Tests must be more tolerant to this.

### PR DESCRIPTION
**Pull request by mgautierfr**
Wait for few (milli)seconds is not enough.
Thread may run sooner or later than expected.

New testiing checks that the following appears **in order**:
- One or several calls without throwing an error
- One (and only) call throwing an `AsyncError`
- Following calls always throwing a CreatorStateError.
- Last call always throws a exception.

Fix #747

### CODE REVIEW

File: test/error_in_creator.cpp [hunk 1]
```diff
@@ -226,6 +226,35 @@ double getWaitTimeFactor() {
 
 class FaultyDelayedItemErrorTest : public ::testing::TestWithParam<ERRORKIND> {};
 
+
+// All the following code "should" thrown a error :
+// - An asyncError on the first call (async_error_thrown == false)
+// - An CreatorStateError on other calls (async_error_thrown == true)
+// But it may not thrown if worker thread has not run.
+// (and only in this case. If a AsyncError has been thrown, other calls MUST throw a CreatorErrorState)
+#define CHECK_ASYNC_EXCEPT(CALL, MUST_FAIL) \
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:235]: It is possible to get rid of the `MUST_FAIL` parameter as follows:

```c++
// finishZimCreation() always waits for workers, so we MUST have an exception.
const bool MUST_FAIL = std::string(#CALL).find("finishZimCreation") != std::string::npos;
```

**Review by veloman-yunkan — COMMENTED** [review]
While reviewing this PR I figured out something that should have been proposed in #496 - shouldn't there be a test for a flow with async errors where `finishZimCreation()` isn't called at the end, so that we can make sure that the `Creator` destructor doesn't rely on that method for clean-up of any effects caused by intercepted asynchronous errors?

File: test/error_in_creator.cpp [hunk 2]
```diff
@@ -234,6 +263,7 @@ TEST_P(FaultyDelayedItemErrorTest, faultyCompressedItem)
   unittests::TempFile temp("zimfile");
   auto tempPath = temp.path();
 
+  bool async_error_thrown = false;
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply test/error_in_creator.cpp:266]: I tend to think of TestSuite (as `FaultyDelayedItemErrorTest`) as provider of fixture (or just a "implementation detail" necessary structure).

`async_error_throw` is not a fixture but a variable describing the context of the running test. It is better to have it declared in the test itself.

File: test/error_in_creator.cpp [hunk 3]
```diff
@@ -283,12 +323,37 @@ TEST_P(FaultyDelayedItemErrorTest, faultyUnCompressedItem)
...
+    // creator.finishZimCreation() is not called
+  }
+
+  EXPECT_THROW(
+      {
+        const zim::Archive archive(tmpFile.path());
+      },
+      zim::ZimFileFormatError
+  );
+}
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:356]: This better be placed in a commit of its own.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
Please fix the commit history during rebase&fixup and we are good.

**Review by veloman-yunkan — APPROVED** [review]
There is one tiny issue that can be fixed before merging without an additional review.

**Comment by kelson42** [comment]
Good to merge now I guess?
