### PR TITLE
Fix parseLongPath() to handle namespaces

### LINKED ISSUE #477: zim::parseLongPath() should handle paths consisting of the namespace only
Currently if a url like `"A"` is given to the function, it throws an error. A more appropriate response should be to return the namespace character(if any) along with an empty string like `(ns, "")`.
This will help in fixing openzim/zim-tools#171. Refer openzim/zim-tools#216.

### PR DESCRIPTION
**Pull request by maneeshpm**
Fixes #477 
If a `path` of length 1 is passed and qualifies as a namespace character, return `(ns, "")`

### CODE REVIEW

**Comment by maneeshpm** [comment]
@veloman-yunkan The changes have been included.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
Did you run unit-tests? The parseLongPath unit test is failing. Please review and modify that unit test respectively, to reflect the updated functionality of `parseLongPath()`. Try to add more corner cases if needed.

File: test/parseLongPath.cpp [hunk 1]
```diff
@@ -32,7 +32,6 @@ namespace
 TEST(ParseLongPathTest, invalid)
 {
   ASSERT_THROW(parseLongPath(""), std::runtime_error);
-  ASSERT_THROW(parseLongPath("A"), std::runtime_error);
   ASSERT_THROW(parseLongPath("A/"), std::runtime_error);
   ASSERT_THROW(parseLongPath("AB"), std::runtime_error);
   ASSERT_THROW(parseLongPath("AB/path"), std::runtime_error);
```
Comment (veloman-yunkan) [inline test/parseLongPath.cpp:37]: I think that from the point of view of consistency, the following cases should be treated as equivalent:

- `A`
- `A/`
- `/A`
- `/A/`

Comment (maneeshpm) [reply test/parseLongPath.cpp:36]: Yes @veloman-yunkan, There is no point in treating them as invalid cases. Modifying the code to accommodate this and adding unit tests for these cases as well.

File: src/tools.cpp [hunk 2]
```diff
@@ -106,9 +106,13 @@ std::tuple<char, std::string> zim::parseLongPath(const std::string& longPath)
 {
   /* Index of the namespace char; discard '/' from absolute paths */
   const unsigned int i = (longPath[0] == '/') ? 1 : 0;
-  if (i + 2 >= longPath.size() || longPath[i] == '/' || longPath[i+1] != '/')
+  if (i + 1 > longPath.size() || longPath[i] == '/' || (i + 2 <= longPath.size() && longPath[i+1] != '/'))
```
Comment (veloman-yunkan) [inline src/tools.cpp:109]: The condition `(i + 2 <= longPath.size() && longPath[i+1] != '/')` will be a little easier to understand if rewritten as `(i + 1 < longPath.size() && longPath[i+1] != '/')` (since `i+1` is used as an index into `longPath` we check that it isn't out of bounds)

File: src/tools.cpp [hunk 3]
```diff
@@ -106,9 +106,13 @@ std::tuple<char, std::string> zim::parseLongPath(const std::string& longPath)
...
     throw std::runtime_error("Cannot parse path");
 
+  /* Handle namespace longPath such as "A" "/A" "A/" "/A/" */
+  if (i + 2 >= longPath.size())     
+    return std::make_tuple(longPath[i], "");
+  
   auto ns = longPath[i];
   auto shortPath = longPath.substr(i+2, std::string::npos);
```
Comment (veloman-yunkan) [inline src/tools.cpp:118]: In general, it is a good practice to have only a single `return` statement in a function. In this case, it is easily achieved by slightly changing how `shortPath` is extracted from `longPath`:

```c++
  auto shortPath = longPath.substr(std::min(i+2, longPath.size()));
```

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
Great!

The two comments below are just suggestions. Since it's a matter of personal taste, feel free to ignore them. But we also need to get back to [your observation ](https://github.com/openzim/libzim/issues/477#issuecomment-766571946) regarding `Archive::findByPath()`. Since `parseLongPath()` now doesn't reject inputs of the form `A/` or `/A/`, `Archive::findByPath()` will work incorrectly in those cases. Please check that hypothesis in the `test/find.cpp` unit test and propose a fix for it, too.

File: src/tools.cpp (hunk 3 above)
Comment (maneeshpm) [reply src/tools.cpp:114]: Yes, this looks much neater. Thanks!

**Comment by maneeshpm** [comment]
@veloman-yunkan `archive::findByPath()` fails for any parameter that has a trailing slash because of a `path.back()++` in the function. In think, removing trailing slash if any solves the issue. 
```c++
Archive::EntryRange<EntryOrder::pathOrder> Archive::findByPath(std::string path) const
{
    /* Removing trailing slash */
    if(path.back() == '/') path.pop_back();
    entry_index_t begin_idx, end_idx;
    if (m_impl->hasNewNamespaceScheme()) {
      ...
    } else {
      ...
    }
    return Archive::EntryRange<EntryOrder::pathOrder>(m_impl, begin_idx.v, end_idx.v);
}
```
Works as expected and passes the build tests.

**Comment by mgautierfr** [comment]
> archive::findByPath() fails for any parameter that has a trailing slash because of a path.back()++ in the function. I think, removing the trailing slash solves the issue.

Why it is failing ? (And how ?)

This should not. The path of a item is just a string of bytes. There is no semantics associated to it (except the namespace part).
The fact that paths look like a file path or a url is because of how we use it (in kiwix). At libzim level, we don't care.

If we search for a `C/foo/` we must return all entries starting by `C/foo/` and we should NOT return `C/foo` or `C/foothing`

**Review by veloman-yunkan — COMMENTED** [review]
Approving. Please squash all your commits into one - we don't need all the history of this PR.

**Comment by veloman-yunkan** [comment]
@mgautierfr makes a good point

> If we search for a C/foo/ we must return all entries starting by C/foo/ and we should NOT return C/foo or C/foothing

Please also add corresponding test cases to `findByPath()`'s unit test.

**Comment by maneeshpm** [comment]
@mgautierfr Sorry, I meant it fails for all namespace urls with trailing slash. This is an implementation issue in `findByPath()` when we want to use it only for namespace parameters such as `A/` or `/A/`. 

Suppose we pass `A/` as the parameter, `findByPath()` assigns `begin_idx` properly, then performs a `path.back()++` which makes the path `A/`->`A0` which is an invalid path for `parseLongPath()` and throws a runtime error when finding `end_idx`.
```
$ zimdump list --ns=M/ khan-academy-videos_fr_amine_2020-06.zim                                                                                            
M/Counter
M/Creator
...
M/Tags
M/Title
X/fulltext/xapian
X/title/xapian
Exception: entry index out of range
```

**Comment by mgautierfr** [comment]
> Sorry, I meant it fails for all namespace urls with trailing slash. This is an implementation issue in findByPath() when we want to use it only for namespace parameters such as A/ or /A/.

You are right. But then, your proposed fix (`if(path.back() == '/') path.pop_back();`) is not good as it removes all trailing slash.

**Comment by maneeshpm** [comment]
@mgautierfr I understand now, thanks for pointing it out! Perhaps I should modify the condition to check if it's actually a namespace url and only then remove the trailing slash if required.

File: src/archive.cpp [hunk 4]
```diff
@@ -261,6 +261,10 @@ namespace zim
     // If we search for prefix a, we must return 0/4
     // A findx with a will return 0
     // A find with b will return 4
+
+    // If path is a namespace url "A/" or "/A/" remove trailing slash
+    if(path.size() <= 3 && path.back() == '/') path.pop_back();
```
Comment (veloman-yunkan) [inline src/archive.cpp:266]: This workaround should be employed only if the archive uses the old namespace scheme.

Besides, the case of the empty path will cause problems (the old code was not protected against that corner case too). I think we can add an `ASSERT` that `path` is not empty.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/archive.cpp (hunk 4 above)
Comment (maneeshpm) [reply src/archive.cpp:266]: @veloman-yunkan so I should modify this to:
```c++
Archive::EntryRange<EntryOrder::pathOrder> Archive::findByPath(std::string path) const
{
    entry_index_t begin_idx, end_idx;
    if (m_impl->hasNewNamespaceScheme()) {
      ...
    } else {
      ASSERT(path.empty(), !=, true)
      if(path.size() <= 3 && path.back() == '/') path.pop_back();
      ...
    }
    return Archive::EntryRange<EntryOrder::pathOrder>(m_impl, begin_idx.v, end_idx.v);
}
```
Is this the correct approach?

Comment (veloman-yunkan) [reply src/archive.cpp:266]: Let the `ASSERT` be outside/above the `if` statement

**Review by veloman-yunkan — APPROVED** [review]

File: src/archive.cpp (hunk 4 above)
Comment (mgautierfr) [reply src/archive.cpp]: It would be better to handle a empty `path` as a special case and returning the same Range than `iterByPath`.

I've used a lot of ASSERT in the past but we should not.
The ASSERT should be use for assertion (things that must be always true. If not, this is a bug) ASSERT may be removed in the future in release mode.

Here we are checking a value coming from the user. We must check it "normally" and throw a correct exception.

Comment (maneeshpm) [reply src/archive.cpp]: @mgautierfr That makes sense. For this particular issue, I guess having a separate `if(path.empty())` will be fine.
```c++
Archive::EntryRange<EntryOrder::pathOrder> Archive::findByPath(std::string path) const
{
    entry_index_t begin_idx, end_idx;
    if(path.empty()){
       begin_idx = m_impl->getStartUserEntry();
       end_idx = m_impl->getEndUserEntry()
    } else if (m_impl->hasNewNamespaceScheme()) {
      ...
    } else {
      if(path.size() <= 3 && path.back() == '/') path.pop_back();
      ...
    }
    return Archive::EntryRange<EntryOrder::pathOrder>(m_impl, begin_idx.v, end_idx.v);
}
```
Is this the change you are suggesting?

Comment (mgautierfr) [reply src/archive.cpp]: Yes.

Can you add test for `/` path also please ? (as if the path is empty)

**Comment by kelson42** [comment]
@mgautierfr I think your review is again needed here.

**Comment by kelson42** [comment]
@maneeshpm Please rebase your branch on latest `HEAD origin/master`.

**Comment by maneeshpm** [comment]
@kelson42 I think that I've messed things up a bit. Can you help me out with handling the rebase?

**Comment by kelson42** [comment]
@maneeshpm You have only one commit now in the PR, not sure if you have squased everything together or if you have lost some commits... but to do a rebase you need to resync your fork (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) and then make in your feature branch:
```
$git fetch
$git rebase origin/master
```

**Comment by maneeshpm** [comment]
@kelson42 Thanks for the info. I am never forgetting that again :sweat_smile:. I have sqashed the commits and this pr contains all the intended changes.

**Comment by mgautierfr** [comment]
There is another use case not handled : `A//` (Namespace `A`, path: `/`).
In this case, we want to increment the last `/`.
And the test `if(path.size() <= 3 && path.back() == '/') path.pop_back();` is not good.

The increment of the last char is a bit more complex that it seems at first sight, maybe we need a specific method.
Or simply parse the long path first and then increment the last char of the parsed short path.

---

It is a matter of style, but I prefer to have the test written on several lines :
```
if(path.size() <= 3 && path.back() == '/') {
  path.pop_back();
}
```

**Comment by maneeshpm** [comment]
@mgautierfr Thats a valid point, parsing the path before beforehand seems to be the correct approach. I agree, in the future having a more sophisticated method for this would be a nice idea.
For now, I am planning the following changes:
```c++
Archive::EntryRange<EntryOrder::pathOrder> Archive::findByPath(std::string path) const
{
    entry_index_t begin_idx, end_idx;
    if (path.empty() || path == "/") {
      begin_idx = m_impl->getStartUserEntry();
      end_idx = m_impl->getEndUserEntry(); 
    } else if (m_impl->hasNewNamespaceScheme()) {
      begin_idx = m_impl->findx('C', path).second;
      path.back()++;
      end_idx = m_impl->findx('C', path).second;
    } else {
      char ns;
      std::tie(ns, path) = parseLongPath(path);
      begin_idx = m_impl->findx(ns, path).second;
      if (path.empty()){
        ns++;
        end_idx = m_impl->findx(ns, path).second;
      } else {
        path.back()++;
        end_idx = m_impl->findx(ns, path).second;
      }
    } 
    return Archive::EntryRange<EntryOrder::pathOrder>(m_impl, begin_idx.v, end_idx.v);
  }
```

I think this is pretty much exhaustive and covers all the unit tests. After this modification, all the invalid paths like the one you mentioned will be handled by parseLongPath by throwing an `std::runtime_error`. One unit test 
```
auto range0 = archive.findByPath("unkwonUrl");
ASSERT_EQ(range0.begin(), range0.end());
```
will be changed from `ASSERT_EQ` to `ASSERT_THROW` due to the nature of parseLongPath.
Is this the right approach?

**Comment by mgautierfr** [comment]
> will be changed from ASSERT_EQ to ASSERT_THROW due to the nature of parseLongPath.

We should not change the API based on the nature of a internal method.
`findByPath` searches for a range of entries starting by the prefix. If no entries start with the given prefix, we return an empty range.
The question is more about what we should do if the user give a invalid path (and what is a invalid path) ?

For a long time, a (long) path was composed of a namespace and a short path. The new api remove this.
Now, we hide the namespace, so a path is simply a (short path). We still have a namespace for compatibility with old zim file but the idea is to hide it. (And it is hidden as a subdirectory in the path)
So there is no invalid path. At worst a path is wrong (pointing to a non existing entry).
And if there is no invalid path, for this method, we must not throw an exception (at least not because the namespace is missing, we may throw other exception as ZimFileFormatError).

**Comment by maneeshpm** [comment]
@mgautierfr That makes sense. Since we are trying to hide the old namespace scheme, I think we should place `parseLongPath()` inside a try-catch block and return an empty range as you mentioned if an error is encountered. This way, the API remains unchanged and we can facilitate a smooth change to the new scheme.

**Comment by maneeshpm** [comment]
@mgautierfr This fix will prevent any error from being thrown in parseLongPath and rather, return an empty range if an "unknown" URL is passed to the function.

**Comment by mgautierfr** [comment]
We should try/catch only the parsing of the url.
If there is a `ZimFileFormatError` thrown when we `findx` we don't want to discard it.

**Comment by maneeshpm** [comment]
@mgautierfr Understood. Made the necessary changes. Is this code structure fine?

**Comment by mgautierfr** [comment]
We are good.
I would have written it this way to avoid the `parseOk` variable and the extra indentation

```
char ns;
try {
  std::tie(ns, path) = parseLongPath(path);
} catch (...) {
  Archive::EntryRange<EntryOrder::pathOrder>(m_impl, 0, 0);
}
begin_idx = m_impl->findx(ns, path).second;
if (path.empty()) {
  ns++;
} else {
  path.back()++;
}
end_idx = m_impl->findx(ns, path).second;
```

But it is a matter of preference, it works anyway.


If @veloman-yunkan is ok, we can merge.

**Comment by maneeshpm** [comment]
Thanks for the suggestion @mgautierfr. This looks much more neater and concise. I will try to follow it in the future as well.

**Comment by kelson42** [comment]
@maneeshpm Your branch would benefit to be rebased on our git master, so we can merge it.

**Comment by maneeshpm** [comment]
@kelson42 rebased to master. Thanks!

**Comment by kelson42** [comment]
@maneeshpm It seems you latest PR breaks on windows, see https://github.com/openzim/libzim/runs/1825653239?check_suite_focus=true

**Comment by maneeshpm** [comment]
@kelson42 Looks like `windows.h` header file has macros for `min` & `max` which are interfering with the code. [See ref](https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included). I think the best way to fix this is by explicitly mentioning our function type like `int k = std::min<int>(3, 4);`. Do I need to open a new issue to fix this?

**Comment by kelson42** [comment]
@maneeshpm yes please. You should have write permission now on this repo, please male you PR here (and not in your fork).
