### PR TITLE
Thread exception

### LINKED ISSUE #475: Creator should properly handle user-code error
Creator spawn worker threads to compress/index the item's content provided by user-code.
Those workers call user-code to get the content (user have to implement the item interface. The code may be written in python/node in case of wrapper).

If something goes wrong in the user-code, we should properly handle it. (For now we are crashing).

After discussion with @veloman-yunkan and @rgaudin we agree :
- To have a "exception slot" in the creator which will be set by workers if a exception is raised by user code.
- Entrance methods `add*` check for the slot and re throw the exception if set (and mark creator as in error).
- Calling user code (potentially in Python) catch the exception and do what it have to do (report the error and stop)
- Any call to `add*` on a error-marked creator also raises a exception.
- [Python] The context manager on the wrapper side catch the exception and properly close the creator without creating the zimfile.

### PR DESCRIPTION
**Pull request by mgautierfr**
~~This is a draft PR, just to track the branch.~~ Now ready to review
Fixes #475
Fixes https://github.com/openzim/python-libzim/issues/153

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr How much work is needed here to complete this PR?

**Comment by mgautierfr** [comment]
Tests are failing because we don't wait enough to have the threads "detecting" the error.
(It is enough on my computer, but on the CI).
I wonder how we should handle that. Simply increase the waiting time or simply don't test that subsequent call are failing (`finishZimCreation` will always detect the error as it waits for all thread to finish, and it would always be tested) ?

**Comment by kelson42** [comment]
@mgautierfr All CI does not pass unfortunately

File: src/writer/creator.cpp [hunk 1]
```diff
@@ -383,13 +393,27 @@ namespace zim
...
+    void Creator::checkError()
+    {
+      if (data->m_errored) {
+        throw std::runtime_error("Creator is in error state");
+      }
+      std::lock_guard<std::mutex> l(data->m_exceptionLock);
+      if (data->m_exceptionSlot) {
+        std::cerr << "ERROR Detected" << std::endl;
+        data->m_errored = true;
+        std::rethrow_exception(data->m_exceptionSlot);
```
Comment (veloman-yunkan) [inline src/writer/creator.cpp:405]: I wonder if rethrowing the exception intercepted in a worker thread makes sense. Because of the asynchronous nature of such error handling (the error originates in one context but is reported in another) it may lead to confusion. What about adding an `AsyncError` exception type that will link to the intercepted exception via a `std::exception_ptr` data member?

File: test/error_in_creator.cpp [hunk 2]
```diff
@@ -0,0 +1,256 @@
...
+
+  writer::Creator creator;
+  creator.configIndexing(true, "eng");
+  creator.configClusterSize(5);
+  creator.startZimCreation(tempPath);
+  auto item = std::make_shared<FaultyItem>("foo", "Foo", "FooContent", false, GetParam());
+  // Exception is not thrown in main thread so error is not detected
+  EXPECT_NO_THROW(creator.addItem(item));
+  // We force the closing of the cluster, so working thread will detect error
+  EXPECT_NO_THROW(creator.addMetadata("A medatata", "A uncompressed metadata", "plain/content"));
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:229]: Is the spelling error in "medatata" intentional?

File: test/error_in_creator.cpp [hunk 3]
```diff
@@ -0,0 +1,256 @@
...
+    FaultyContentProvider(const std::string& content, ERRORKIND fault)
+      : writer::StringProvider(content),
+        fault(fault)
+    {}
+
+  zim::size_type getSize() const {
+    THROW_ERROR(EXCEPTION_CONTENTPROVIDER_SIZE)
+    auto size = writer::StringProvider::getSize();
+    if (fault == ERRORKIND::WRONG_SIZE_CONTENTPROVIDER) {
+      return size + 1;
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:65]: It would be nice to check that an underreported size leads to an error too

**Comment by mgautierfr** [comment]
Indeed, it is usleep on Windows.
But usleep is used to wait for the thread and is related to the problem explain in my [previous comment](https://github.com/openzim/libzim/pull/496#issuecomment-1222751791)
Better wait for a answer to my question and fix it if needed.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
1. Some of the errors checked by the new unit test come from `ASSERT`s that are [disabled in a release build](https://github.com/openzim/libzim/blob/8.0.0/src/debug.h#L28-L30). This will lead to bug reports similar to #670 (see https://github.com/openzim/libzim/issues/670#issuecomment-1040779500).
1. Handling of errors during ZIM creation must be documented.

File: src/writer/workers.cpp [hunk 4]
```diff
@@ -71,7 +84,12 @@ namespace zim
           }
           creatorData->clusterToWrite.popFromQueue(cluster);
           cluster->setOffset(offset_t(lseek(creatorData->out_fd, 0, SEEK_CUR)));
-          cluster->write(creatorData->out_fd);
+          try {
+            cluster->write(creatorData->out_fd);
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply src/writer/workers.cpp:88]: We try to to catch exception coming from the user code here.
And it is `Cluster::write()` which may throw them (by using user `ContentProvider`).
Other code should not throw a exception.

(Same for the try around the `task->run`)

[the remark this answers is not in the document]
Comment (veloman-yunkan) [reply src/writer/workers.cpp:88]: I understand that with current code an exception may only come from `Cluster::write()`. But that's not a good reason for using such a narrow scope for the `try` block. If you want to solve the issue of exception handling across threads for the long run, a future proof solution is to intercept any possible exception in the loop.

File: src/writer/creator.cpp (hunk 1 above)
Comment (mgautierfr) [reply src/writer/creator.cpp:405]: It looks like a good idea but it seams that we can do nothing but store and rethrow a `std::exception_ptr`.
So it is useless to store in in a AsyncError, especially we want to know the error message of the original exception and a `AsyncError` we may throw cannot access it.
(Or maybe you know how to)

Comment (veloman-yunkan) [reply src/writer/creator.cpp:405]: > Edit: My bad, we can. We can rethrow it in a try/catch.

Exactly. That's what I had in mind. And I also think that it will be useful to utilize that trick to extract the error message from the intercepted exception in `AsyncError::what()` (or in the constructor of `AsyncError`) and construct an informative error message. Then only code that needs to know the exact type of the intercepted exception will have to have an extra `try{}catch(){}` inside `catch(const AsyncError& ex){}`. Yet that will make sense only in the following cases:

1. when it's possible to recover from that particular error situation
2. or when there are necessary clean-up actions to be performed specific to such a failure

File: test/error_in_creator.cpp [hunk 5]
```diff
@@ -0,0 +1,261 @@
...
+  EXPECT_NO_THROW(creator.addMetadata("A metadata", "A compressed (default) metadata"));
+  // give a chance to threads to detect the error
+  // For compressed cluster, the cluster task is a bit longer to use the contentProvider
+  // (memory initialisation of the compression stream ?)
+  usleep(1000000);
+  // We detect it for any call after
+  EXPECT_THROW(creator.addMetadata("Title", "This is a title"), std::runtime_error);
+  EXPECT_THROW(creator.addIllustration(48, "PNGBinaryContent48"), std::runtime_error);
+  EXPECT_THROW(creator.addRedirection("foo2", "FooRedirection", "foo"), std::runtime_error);
+  EXPECT_THROW(creator.finishZimCreation(), std::runtime_error);
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:217]: `std::runtime_error` -> `AsyncError`

File: test/error_in_creator.cpp [hunk 6]
```diff
@@ -0,0 +1,261 @@
...
+  EXPECT_NO_THROW(creator.addMetadata("A metadata", "A uncompressed metadata", "plain/content"));
+  // give a chance to threads to detect the error
+  // Less to wait for as we don't compress the content and the writer thread
+  // (the one using the contentProvider) detect the error sooner
+  usleep(10000);
+  // But we detect it for any call after
+  EXPECT_THROW(creator.addMetadata("Title", "This is a title"), std::runtime_error);
+  EXPECT_THROW(creator.addIllustration(48, "PNGBinaryContent48"), std::runtime_error);
+  EXPECT_THROW(creator.addRedirection("foo2", "FooRedirection", "foo"), std::runtime_error);
+  EXPECT_THROW(creator.finishZimCreation(), std::runtime_error);
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:242]: `std::runtime_error` -> `AsyncError`

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
Please rebase/fixup and clean the history of this PR for the next (hopefully, final) review

File: include/zim/error.h [hunk 7]
```diff
@@ -47,6 +47,34 @@ namespace zim
...
+      explicit AsyncError(const std::exception_ptr exception)
+       : std::runtime_error(""),
+         m_exception(exception),
+         m_message("Unknown exception")
+      {
+        try {
+          std::rethrow_exception(m_exception);
+        } catch (const std::exception& e) {
+          m_message = e.what();
+        } catch (...) {}
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply include/zim/error.h:63]: 1. The problem is that `what` must return a pointer valid `at least until the exception object from which it is obtained is destroyed, or until a non-const member function on the exception object is called.` (https://en.cppreference.com/w/cpp/error/exception/what)

Generating the error message on fly with a free/static function doesn't guaranty that.

2. Agree

[the remark this answers is not in the document]
Comment (mgautierfr) [reply include/zim/error.h]: #2 has been fixed in a fixup commit

**Comment by kelson42** [comment]
@mgautierfr I have updated to comment to say it "fixes #475"

File: include/zim/error.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (veloman-yunkan) [reply include/zim/error.h]: > 1. The problem is that `what` must return a pointer valid `at least until the exception object from which it is obtained is destroyed, or until a non-const member function on the exception object is called.` (https://en.cppreference.com/w/cpp/error/exception/what)

But you call `AsyncError::buildErrorMessage()` in the constructor and initialize `std::runtime_error` with the result

File: test/error_in_creator.cpp [hunk 8]
```diff
@@ -211,10 +212,10 @@ TEST_P(FaultyDelayedItemErrorTest, faultyCompressedItem)
...
   usleep(1000000);
   // We detect it for any call after
-  EXPECT_THROW(creator.addMetadata("Title", "This is a title"), std::runtime_error);
-  EXPECT_THROW(creator.addIllustration(48, "PNGBinaryContent48"), std::runtime_error);
-  EXPECT_THROW(creator.addRedirection("foo2", "FooRedirection", "foo"), std::runtime_error);
-  EXPECT_THROW(creator.finishZimCreation(), std::runtime_error);
+  EXPECT_THROW(creator.addMetadata("Title", "This is a title"), AsyncError);
+  EXPECT_THROW(creator.addIllustration(48, "PNGBinaryContent48"), AsyncError);
+  EXPECT_THROW(creator.addRedirection("foo2", "FooRedirection", "foo"), AsyncError);
+  EXPECT_THROW(creator.finishZimCreation(), AsyncError);
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:218]: Shouldn't only the first one be `AsyncError`? After that the creator transitions to an error state and throws regular `std::runtime_error` exceptions on any attempt to use it. BTW, what about introducing a separate exception type for the latter case?

File: test/error_in_creator.cpp [hunk 9]
```diff
@@ -236,10 +237,10 @@ TEST_P(FaultyDelayedItemErrorTest, faultyUnCompressedItem)
...
   usleep(10000);
   // But we detect it for any call after
-  EXPECT_THROW(creator.addMetadata("Title", "This is a title"), std::runtime_error);
-  EXPECT_THROW(creator.addIllustration(48, "PNGBinaryContent48"), std::runtime_error);
-  EXPECT_THROW(creator.addRedirection("foo2", "FooRedirection", "foo"), std::runtime_error);
-  EXPECT_THROW(creator.finishZimCreation(), std::runtime_error);
+  EXPECT_THROW(creator.addMetadata("Title", "This is a title"), AsyncError);
+  EXPECT_THROW(creator.addIllustration(48, "PNGBinaryContent48"), AsyncError);
+  EXPECT_THROW(creator.addRedirection("foo2", "FooRedirection", "foo"), AsyncError);
+  EXPECT_THROW(creator.finishZimCreation(), AsyncError);
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:243]: Same here

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: include/zim/error.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (mgautierfr) [reply include/zim/error.h]: Haa, yes indeed. Thanks

File: test/error_in_creator.cpp (hunk 8 above)
Comment (mgautierfr) [reply test/error_in_creator.cpp]: Indeed. I've created a `CreatorStateError` for this.

File: include/zim/error.h [hunk 10]
```diff
@@ -53,32 +53,31 @@ namespace zim
...
-      std::string m_message;
+
+    private: // function
+      static std::string buildErrorMessage(const std::exception_ptr exception) {
+        try {
+          std::rethrow_exception(exception);
+        } catch (const std::exception& e) {
+          std::stringstream ss;
+          ss << "Asynchronous error: ";
+          ss << typeid(exception).name() << std::endl;
```
Comment (veloman-yunkan) [inline include/zim/error.h:74]: `exception` -> `e`

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

**Comment by veloman-yunkan** [comment]
The concerns raised in the [first review](https://github.com/openzim/libzim/pull/496#pullrequestreview-1081606816) have not been addressed:

> 1. Some of the errors checked by the new unit test come from `ASSERT`s that are [disabled in a release build](https://github.com/openzim/libzim/blob/8.0.0/src/debug.h#L28-L30). This will lead to bug reports similar to #670 (see https://github.com/openzim/libzim/issues/670#issuecomment-1040779500).
> 2. Handling of errors during ZIM creation must be documented.

**Comment by mgautierfr** [comment]
Fixed. (I will move the three new commits a bit upper in the git history when rebase-fixup)

**Review by veloman-yunkan — COMMENTED** [review]
There were a few typos in the documentation, but I guess you can fix them as you rebase and fixup.

**Comment by mgautierfr** [comment]
Fixup-rebased. Ready for another review.

File: include/zim/writer/creator.h [hunk 11]
```diff
@@ -51,8 +51,13 @@ namespace zim
      * The current (documented) conditions when a exception is thrown are:
      * - When a entry cannot be added (mainly because a entry with the same path has already been added)
      *    A `zim::InvalidEntry` will be thrown. The creator will still be in a valid state and the creation can continue.
-     * - A incoherence has been detected in user implementation (of Item, ContentProvider, IndexData, ...)
-     *    A `zim::IncoherentImplementationError` will be thrown.
+     * - An exception has been thrown in a worker thread.
+     *    This exception will be catch and rethrown through a `zim::AsyncError`.
+     *    The creator will be set in a invalid state and creation cannot continue.
+     * - The creator is in error state.
+     *    A `zim::CreatorStateError` will be thrown.
```
Comment (veloman-yunkan) [inline include/zim/writer/creator.h:58]: These two lines better belong to the commit where `CreatorStateError` is introduced

File: src/writer/creator.cpp [hunk 12]
```diff
@@ -381,8 +381,7 @@ namespace zim
       while (true) {
          auto r = read(out_fd, batch_read, 1024);
          if (r == -1) {
-           perror("Cannot read");
-           throw std::runtime_error("oups");
+           throw std::runtime_error(std::strerror(errno));
```
Comment (veloman-yunkan) [inline src/writer/creator.cpp:384]: Why don't you move this commit ("Make zim::writer::Creator thrown better exception.") earlier in history?

File: test/error_in_creator.cpp [hunk 13]
```diff
@@ -207,10 +207,19 @@ TEST_P(FaultyDelayedItemErrorTest, faultyCompressedItem)
...
+  // Too long and all tests will wait to much and developpers hate to wait
+  // Not enough and error is not deteced and tests fail (and developpers hate failing tets)
+  // The exacte value is specific to each computer, so we need to make this configurable.
+  // We use a base and we multiply it by a factor taken from env variable.
+  long sleep_time = 1000000; // Default value is set to a factor 10 above what is needed to work on my (fast) computer
+  char* str_time_factor = std::getenv("WAIT_TIME_FACTOR_TEST");
+  if (str_time_factor) {
+    // Yes, if user set a "non int" value, sleep_time will be 0. But not our problem here
+    sleep_time *= atoi(str_time_factor);
+  }
```
Comment (veloman-yunkan) [inline test/error_in_creator.cpp:222]: Duplication with the other unit test (`FaultyDelayedItemErrorTest.faultyUnCompressedItem`). You can get rid of it by introducing a helper function `double getWaitTimeFactor()` (and I meant `double` so developers hating to wait have an option to lower the wait time).

File: .github/workflows/ci.yml [hunk 14]
```diff
@@ -50,9 +50,10 @@ jobs:
           export LD_LIBRARY_PATH=$HOME/BUILD_${{matrix.target}}/INSTALL/lib:$HOME/BUILD_${{matrix.target}}/INSTALL/lib64
           cd build
           ninja download_test_data
-          meson test --verbose
+          meson test -t 0 --verbose
```
Comment (veloman-yunkan) [inline .github/workflows/ci.yml:53]: I guess that this change was needed to find out the value for the waiting factors on some CI platforms, but it looks like the new unit test simply gets stuck on some of them. In any case this change must not make its way into master.

File: .github/workflows/ci.yml [hunk 15]
```diff
@@ -76,7 +77,9 @@ jobs:
         run: |
           cd build
           ninja download_test_data
-          meson test --verbose
+          meson test -t 0 --verbose
```
Comment (veloman-yunkan) [inline .github/workflows/ci.yml:80]: I guess that this change was needed to find out the value for the waiting factors on some CI platforms, but it looks like the new unit test simply gets stuck on some of them. In any case this change must not make its way into master.

File: .github/workflows/ci.yml [hunk 16]
```diff
@@ -172,13 +175,14 @@ jobs:
       run: |
         cd $HOME/libzim/build
         ninja download_test_data
-        meson test --verbose
+        meson test -t 0 --verbose
```
Comment (veloman-yunkan) [inline .github/workflows/ci.yml:178]: I guess that this change was needed to find out the value for the waiting factors on some CI platforms, but it looks like the new unit test simply gets stuck on some of them. In any case this change must not make its way into master.

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/writer/creator.cpp (hunk 12 above)
Comment (mgautierfr) [reply src/writer/creator.cpp:384]: Done

File: .github/workflows/ci.yml (hunk 14 above)
Comment (mgautierfr) [reply .github/workflows/ci.yml]: Yes, this is removed.

File: .github/workflows/ci.yml (hunk 15 above)
Comment (mgautierfr) [reply .github/workflows/ci.yml]: Yes, this is removed.

File: .github/workflows/ci.yml (hunk 16 above)
Comment (mgautierfr) [reply .github/workflows/ci.yml]: Yes, this is removed.

File: test/error_in_creator.cpp [hunk 17]
```diff
@@ -0,0 +1,256 @@
...
+
+    virtual std::string getContent() const {
+      THROW_ERROR(GET_INDEXDATA_CONTENT)
+      return "FooContent";
+    }
+
+    virtual std::string getKeywords() const {
+      THROW_ERROR(GET_INDEXDATA_KEYWORD)
+      return "";
+    }
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply test/error_in_creator.cpp]: Move in https://github.com/openzim/libzim/pull/727

**Review by veloman-yunkan — COMMENTED** [review]
Please rebase&fixup for final review.

**Comment by mgautierfr** [comment]
> Please rebase&fixup for final review.

Done

File: src/writer/creator.cpp [hunk 18]
```diff
@@ -265,13 +273,16 @@ namespace zim
...
       TINFO("Waiting for workers");
       // wait all cluster compression has been done
+      // If we are in error state, threads have been stoped and waiting_task
+      // will never reach 0, so no need to wait.
       unsigned int wait = 0;
       do {
         microsleep(wait);
         wait += 10;
-      } while(ClusterTask::waiting_task.load() > 0);
+      } while(ClusterTask::waiting_task.load() > 0 && !data->isErrored());
```
Comment (veloman-yunkan) [inline src/writer/creator.cpp:282]: This is duplication with `XapianHandler::waitNoMoreTask()`.  There is also some duplication across `IndexTask` and `ClusterTask` due to maintenance of the waiting task count. All code duplication can be eliminated via an introduction of an auxiliary template class.

Draft

```c++
template<class T>
class TrackableTask : public Task {
public:
    TrackableTask(const TrackableTask&) = delete;
    TrackableTask& operator=(const TrackableTask&) = delete;
    TrackableTask() { ++waitingTaskCount; }
    virtual ~TrackableTask() { --waitingTaskCount; }

    void waitNoMoreTask(const CreatorData* data)
    {
        unsigned int wait = 0;
        do {
            microsleep(wait);
            wait += 10;
        } while(waitingTaskCount.load() > 0 && !data->isErrored());
    }

private:
    static std::atomic<unsigned long> waitingTaskCount;
};

class ClusterTask : TrackableTask<ClusterTask>
{
    ...
};

class IndexTask : TrackableTask<IndexTask>
{
    ... 
};
```

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]

File: src/writer/creatordata.h [hunk 19]
```diff
@@ -59,7 +59,7 @@ namespace zim
         typedef std::vector<std::string> MimeTypesList;
         typedef std::vector<Cluster*> ClusterList;
         typedef Queue<Cluster*> ClusterQueue;
-        typedef Queue<Task*> TaskQueue;
+        typedef Queue<std::shared_ptr<Task>> TaskQueue;
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply src/writer/creatordata.h:62]: Because the smart pointer is store in the generic `Queue`.
And this `Queue` is also used to pass cluster to `clusterWriter` worker.
And it is using `getHead` which copy (not move) the head value of the queue.

We can probably adapt the queue depending if we pass a `unique_ptr` or something else but I think it is simpler to state that we need a copyable object to store it in the queue.

File: src/writer/creator.cpp (hunk 18 above)
Comment (mgautierfr) [reply src/writer/creator.cpp:282]: Indeed, good idea.

File: test/error_in_creator.cpp [hunk 20]
```diff
@@ -264,20 +279,30 @@ TEST_P(FaultyDelayedItemErrorTest, faultyUnCompressedItem)
   EXPECT_THROW(creator.finishZimCreation(), CreatorStateError);
 }
 
+#if defined(ENABLE_XAPIAN)
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply test/error_in_creator.cpp:282]: On windows cross compilation, the `#if defined` seems somehow in conflict with other macro (I suspect `INSTANTIATE_TEST_CASE_P`). You can see that in : https://github.com/openzim/libzim/actions/runs/3097036712/jobs/5013266248

By moving the conditional compilation around `INSTANTIATE_TEST_CASE_P` it works.
I've added a comment in `test/error_in_creator.cpp` to be explicit about this.

**Comment by mgautierfr** [comment]
Last push-force split a commit in the history (`Make zim::writer::Creator thrown better exception`)  and create a fixup commit for `Introduce CreatorError and InvalidEntry`. 4 commits are added at the end. Other commits are unchanged.

File: src/writer/creator.cpp [hunk 21]
```diff
@@ -164,12 +165,14 @@ namespace zim
 
     void Creator::addMetadata(const std::string& name, const std::string& content, const std::string& mimetype)
     {
+      checkError();
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply src/writer/creator.cpp:169]: It is not really justified (except maybe to avoid create the contentProvider if the creator is already in error state).
But I don't think it hurts to check error too much.

File: test/error_in_creator.cpp [hunk 22]
```diff
@@ -175,6 +176,7 @@ TEST_P(FaultyItemErrorTest, faultyItem)
   EXPECT_NO_THROW(creator.finishZimCreation());
 }
 
+#if defined(ENABLE_XAPIAN)
```
[the remark this answers is not in the document]
Comment (mgautierfr) [reply test/error_in_creator.cpp:189]: See answer on the other same question.

File: src/writer/clusterWorker.cpp [hunk 23]
```diff
@@ -21,7 +21,8 @@
 
 #include "cluster.h"
 
-std::atomic<unsigned long> zim::writer::ClusterTask::waiting_task(0);
+template<>
+std::atomic<unsigned long> zim::writer::TrackableTask<zim::writer::ClusterTask>::waitingTaskCount(0);
```
Comment (veloman-yunkan) [inline src/writer/clusterWorker.cpp:25]: Why don't you define this and its `IndexTask` sibling in `writer/workers.h`?

```c++
template<class T>
std::atomic<unsigned long> zim::writer::TrackableTask<T>::waitingTaskCount(0);
```

**Review by veloman-yunkan — COMMENTED** [review]
Please fix the only last comment, and rebase-fixup for formal approval to merge.

File: src/writer/clusterWorker.cpp (hunk 23 above)
Comment (mgautierfr) [reply src/writer/clusterWorker.cpp]: It was to avoid a multiple definition of the static member.
But it seems that with template, it is a bit different and the actual definition is made only once.

Fixed with a fixup! commit

**Review by veloman-yunkan — COMMENTED** [review]
LGTM. You know why I didn't approve.

**Comment by mgautierfr** [comment]
Done :)

**Review by veloman-yunkan — APPROVED** [review]
